FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build
WORKDIR /src

COPY *.csproj ./
RUN dotnet restore

COPY . ./
RUN dotnet publish -c Release -o dist

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1 as deploy
WORKDIR /dist
COPY --from=build /src/dist .
ENTRYPOINT ["dotnet","api.dll"]